#include "testoptions.h"
//void motor_setup(void);
//void go_north();
//void go_south();
//void go_south_west();
//void go_south_east();
//void go_east();
//void go_west();
//void go_north_west();
//void go_north_east();
//void go_stop();
